#!/bin/bash
#build
#usage: build testCar
#gcc -Wall -pthread -o $1 $1.c -lpigpio -lrt
echo "Compile..."
g++ -Wall -c main.cpp
g++ -Wall -c control.cpp

echo "Link..."
g++ -Wall -pthread main.o control.o -lpigpio -lrt -o carControl
