#!/bin/bash
#build
#usage: build testCar
#gcc -Wall -pthread -o $1 $1.c -lpigpio -lrt

BINDIR='../../../bin'

echo "Compile..."
g++ -Wall -c test1.cpp -I ./PIGPIO
g++ -Wall -c main.cpp -I ./PIGPIO
g++ -Wall -c control.cpp -I ./PIGPIO

echo "Link..."
g++ -Wall -pthread main.o control.o -lpigpio -lrt -o $BINDIR/carControl

g++ -Wall -pthread test1.o control.o -lpigpio -lrt -o $BINDIR/test1
